// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindRCS():Promise<string>;

export function GetLicenseInfo():Promise<Record<string, any>>;

export function GetPlatform():Promise<string>;

export function GetStatus():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<string>;

export function PrepareLogin(arg1:string):Promise<string>;

export function StartWorker():Promise<string>;

export function Stop():Promise<string>;

export function StopWorker():Promise<string>;
