// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindRCS() {
  return ObfuscatedCall(0, []);
}

export function GetLicenseInfo() {
  return ObfuscatedCall(1, []);
}

export function GetPlatform() {
  return ObfuscatedCall(2, []);
}

export function GetStatus() {
  return ObfuscatedCall(3, []);
}

export function Login(arg1, arg2) {
  return ObfuscatedCall(4, [arg1, arg2]);
}

export function Logout() {
  return ObfuscatedCall(5, []);
}

export function PrepareLogin(arg1) {
  return ObfuscatedCall(6, [arg1]);
}

export function StartWorker() {
  return ObfuscatedCall(7, []);
}

export function Stop() {
  return ObfuscatedCall(8, []);
}

export function StopWorker() {
  return ObfuscatedCall(9, []);
}
